spring:
  application:
    name: dazzi

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dazzi
    username: dazzi
    password: 19980304

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id:
            client-secret:
            redirect-uri:
            authorization-grant-type: authorization_code
            scope: openid, profile
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
            jwk-set-uri: https://kauth.kakao.com/oauth/jwks

jwt:
  secret:


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug